### ISSUE TITLE
Enable writers to unrequest an article

### ISSUE THREAD

**Issue by ChrisWolfgang** [draftdev/writer-portal#12]
Writers currently cannot unrequest an assignment. Writers have contacted me to revert an accidental request. We also have duplicate requests. Is it possible to enable writers to unrequest assignments on their own?

**Comment by karllhughes** [comment]
@ChrisWolfgang done. Here's a quick video demonstration: https://www.loom.com/share/15a3ba3dc96944e89779bcb2723204d0

cc @KSiig
